name: Checkout
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            a
      - name: List Files after
        run: ls -a