name: Workflow Run
on:
  workflow_run:
    workflows: [04checkout]
    types: [completed]
    branches:
      - main
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because '04checkout' was completed"
